apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tlb2mnu1b-nodejs-gitops
  description: This is GitOps manifest for tlb2mnu1b-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=tlb2mnu1b-nodejs
    backstage.io/kubernetes-id: tlb2mnu1b-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tlb2mnu1b-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tlb2mnu1b-nodejs
