apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tlb2mnu1b-nodejs
  janus-idp.io/tekton: tlb2mnu1b-nodejs
  backstage.io/kubernetes-id: tlb2mnu1b-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tlb2mnu1b-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
